import { IWord } from '../../../types/types';

const wordListEx:IWord[] = [
  {
    id: '5e9f5ee35eb9e72bc21af4b5',
    group: 0,
    page: 1,
    word: 'approach',
    image: 'files/02_0022.jpg',
    audio: 'files/02_0022.mp3',
    audioMeaning: 'files/02_0022_meaning.mp3',
    audioExample: 'files/02_0022_example.mp3',
    textMeaning: 'To <i>approach</i> something means to move close to it.',
    textExample: 'The boy <b>approached</b> his school.',
    transcription: '[əpróutʃ]',
    textExampleTranslate: 'Мальчик приблизился к своей школе',
    textMeaningTranslate: 'Подойти к чему-то - значит приблизиться к нему',
    wordTranslate: 'подходить'
  },
  {
    id: '5e9f5ee35eb9e72bc21af4b6',
    group: 0,
    page: 1,
    word: 'chemical',
    image: 'files/02_0024.jpg',
    audio: 'files/02_0024.mp3',
    audioMeaning: 'files/02_0024_meaning.mp3',
    audioExample: 'files/02_0024_example.mp3',
    textMeaning: 'A <i>chemical</i> is something that scientists use in chemistry.',
    textExample: 'The scientist mixed the <b>chemicals</b>.',
    transcription: '[kémikəl]',
    textExampleTranslate: 'Ученый смешал химикаты',
    textMeaningTranslate: 'Химическое вещество - это то, что ученые используют в химии',
    wordTranslate: 'химический'
  },
  {
    id: '5e9f5ee35eb9e72bc21af4b9',
    group: 0,
    page: 1,
    word: 'evil',
    image: 'files/02_0026.jpg',
    audio: 'files/02_0026.mp3',
    audioMeaning: 'files/02_0026_meaning.mp3',
    audioExample: 'files/02_0026_example.mp3',
    textMeaning: '<i>Evil</i> describes something or someone bad or cruel, not good.',
    textExample: 'They felt a strange, <b>evil</b> presence as they got closer to the house.',
    transcription: '[íːvəl]',
    textExampleTranslate: 'Они почувствовали странное злое присутствие, когда приблизились к дому',
    textMeaningTranslate: 'Зло описывает что-то или кого-то плохого или жестокого, а не хорошего',
    wordTranslate: 'злой'
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ba',
    group: 0,
    page: 1,
    word: 'experiment',
    image: 'files/02_0027.jpg',
    audio: 'files/02_0027.mp3',
    audioMeaning: 'files/02_0027_meaning.mp3',
    audioExample: 'files/02_0027_example.mp3',
    textMeaning: 'An <i>experiment</i> is a test that you do to see what will happen.',
    textExample: 'The student did an <b>experiment</b> in science class.',
    transcription: '[ikspérəmənt]',
    textExampleTranslate: 'Студент сделал эксперимент в классе науки',
    textMeaningTranslate: 'Эксперимент - это тест, который вы проводите, чтобы увидеть, что произойдет',
    wordTranslate: 'эксперимент'
  },
  {
    id: '5e9f5ee35eb9e72bc21af4bb',
    group: 0,
    page: 1,
    word: 'laboratory',
    image: 'files/02_0029.jpg',
    audio: 'files/02_0029.mp3',
    audioMeaning: 'files/02_0029_meaning.mp3',
    audioExample: 'files/02_0029_example.mp3',
    textMeaning: 'A <i>laboratory</i> is a room where a scientist works.',
    textExample: 'My mother works in a <b>laboratory</b>.',
    transcription: '[lǽbərətɔ̀ːri]',
    textExampleTranslate: 'Моя мама работает в лаборатории',
    textMeaningTranslate: 'Лаборатория - это комната, где работает ученый',
    wordTranslate: 'лаборатория'
  },
];

export default wordListEx;